<a href="https://colab.research.google.com/github/eksq1/dodo/blob/main/inclass/0420_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np

In [1]:
from sklearn.datasets import load_iris

iris_dataset = load_iris() # 붓꽃 데이터셋을 적재합니다.

In [2]:
print(iris_dataset)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], test_size = 0.2)
# 데이터셋을 랜덤하게 80%의 훈련셋과 20%의 테스트셋으로 분리합니다.


In [4]:
print(X_train)

[[5.4 3.  4.5 1.5]
 [6.7 2.5 5.8 1.8]
 [6.4 2.9 4.3 1.3]
 [6.  2.2 5.  1.5]
 [7.2 3.  5.8 1.6]
 [6.5 3.2 5.1 2. ]
 [7.2 3.6 6.1 2.5]
 [6.3 3.3 6.  2.5]
 [4.5 2.3 1.3 0.3]
 [6.1 3.  4.9 1.8]
 [6.1 2.9 4.7 1.4]
 [5.5 3.5 1.3 0.2]
 [7.7 2.6 6.9 2.3]
 [5.  2.  3.5 1. ]
 [7.6 3.  6.6 2.1]
 [6.5 3.  5.8 2.2]
 [6.6 3.  4.4 1.4]
 [6.4 2.8 5.6 2.2]
 [7.  3.2 4.7 1.4]
 [5.9 3.2 4.8 1.8]
 [6.4 2.8 5.6 2.1]
 [7.7 2.8 6.7 2. ]
 [6.5 3.  5.2 2. ]
 [4.6 3.6 1.  0.2]
 [6.2 3.4 5.4 2.3]
 [4.9 3.1 1.5 0.1]
 [6.5 2.8 4.6 1.5]
 [6.1 2.8 4.  1.3]
 [4.8 3.1 1.6 0.2]
 [6.6 2.9 4.6 1.3]
 [5.7 2.8 4.1 1.3]
 [6.1 2.6 5.6 1.4]
 [6.4 3.1 5.5 1.8]
 [4.8 3.4 1.9 0.2]
 [5.  3.5 1.6 0.6]
 [6.3 3.4 5.6 2.4]
 [4.6 3.4 1.4 0.3]
 [5.7 2.6 3.5 1. ]
 [5.1 3.8 1.5 0.3]
 [6.7 3.1 5.6 2.4]
 [5.7 3.  4.2 1.2]
 [5.4 3.7 1.5 0.2]
 [6.9 3.1 5.1 2.3]
 [4.7 3.2 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [7.7 3.8 6.7 2.2]
 [4.8 3.  1.4 0.1]
 [5.4 3.4 1.7 0.2]
 [5.2 2.7 3.9 1.4]
 [4.9 2.5 4.5 1.7]
 [5.9 3.  5.1 1.8]
 [5.6 2.7 4.2 1.3]
 [4.9 2.4 3.

In [5]:
print(y_train)

[1 2 1 2 2 2 2 2 0 2 1 0 2 1 2 2 1 2 1 1 2 2 2 0 2 0 1 1 0 1 1 2 2 0 0 2 0
 1 0 2 1 0 2 0 0 2 0 0 1 2 2 1 1 2 1 0 2 1 1 0 2 0 2 2 1 0 1 2 1 0 1 0 2 0
 2 1 2 0 0 0 0 0 0 2 0 0 1 0 1 1 2 0 0 0 1 2 0 2 1 2 2 1 1 2 0 2 0 1 1 2 2
 2 1 0 0 1 1 1 2 0]


In [6]:
print("특성1 범위: ", "[", min(X_train[:, 0]), ",", max(X_train[:, 0]), "]")
print("특성2 범위: ", "[", min(X_train[:, 1]), ",", max(X_train[:, 1]), "]")
print("특성3 범위: ", "[", min(X_train[:, 2]), ",", max(X_train[:, 2]), "]")
print("특성4 범위: ", "[", min(X_train[:, 3]), ",", max(X_train[:, 3]), "]")

특성1 범위:  [ 4.3 , 7.7 ]
특성2 범위:  [ 2.0 , 4.4 ]
특성3 범위:  [ 1.0 , 6.9 ]
특성4 범위:  [ 0.1 , 2.5 ]


In [7]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(X_train)

X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [8]:
print("표준화된 특성1 범위: ", "[", min(X_train_std[:, 0]), ",", max(X_train_std[:, 0]), "]")
print("표준화된 특성2 범위: ", "[", min(X_train_std[:, 1]), ",", max(X_train_std[:, 1]), "]")
print("표준화된 특성3 범위: ", "[", min(X_train_std[:, 2]), ",", max(X_train_std[:, 2]), "]")
print("표준화된 특성4 범위: ", "[", min(X_train_std[:, 3]), ",", max(X_train_std[:, 3]), "]")


표준화된 특성1 범위:  [ -1.8678574382647375 , 2.238208482058617 ]
표준화된 특성2 범위:  [ -2.4901878026795394 , 3.2656234908333603 ]
표준화된 특성3 범위:  [ -1.5789057048155308 , 1.747084295212427 ]
표준화된 특성4 범위:  [ -1.450908505394127 , 1.64436297278001 ]


In [9]:
from sklearn.svm import SVC

svm_model = SVC(kernel='rbf', C=8, gamma=0.1)

svm_model.fit(X_train_std, y_train) # SVM 분류 모델 훈련

SVC(C=8, gamma=0.1)

In [10]:
y_pred = svm_model.predict(X_test_std) # 테스트

In [11]:
print("예측된 라벨:", y_pred)
print("ground-truth 라벨:", y_test)

예측된 라벨: [1 2 1 2 0 1 1 2 1 0 0 0 0 0 1 2 1 0 0 1 1 0 1 2 0 0 1 2 2 1]
ground-truth 라벨: [1 2 1 2 0 1 1 1 1 0 0 0 0 0 1 2 1 0 0 1 1 0 1 2 0 0 1 2 2 1]


In [16]:
print("prediction accuracy: {:.2f}".format(np.mean(y_pred == y_test)))

prediction accuracy: 0.97
